name: unit-tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run Rocker container...
        run: 
          cd .docker
          docker-compose up -d

      - name: Installing composer dependencies...
        run: docker-compose exec api composer install

      - name: Copying test env...
        run: cp .env.test .env

      - name: Migrating tables and seeding...
        run: docker-compose exec api php artisan migrate --seed

      - name: Run PHPUnit tests...
        run: docker-compose exec api vendor/bin/phpunit