name: unit-tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

        container:
          image: jsr-pay-api:latest  # Replace with your project's Docker image
          volumes:
            - .:/app

    steps:
      # Install PHP and PostgreSQL extensions
      - name: Setup PHP and PostgreSQL
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql

      # Install dependencies
      - name: Install dependencies
        run: docker-compose run --rm app composer install --prefer-dist --no-progress

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: docker-compose run --rm app vendor/bin/phpunit --configuration phpunit.xml