name: unit-tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          version: "11.1.3"
          configuration: "./phpunit.xml"