name: unit-tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copying test env
        run: cp .env.test .env

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml